apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kingjames227/three-tier-app-backend:v1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGODB_URL
