name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up image tag from Git commit SHA
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/three-tier-app-backend:${{ env.IMAGE_TAG }} .

      - name: Push backend Docker image
        run: |

          docker push ${{ secrets.DOCKER_USERNAME }}/three-tier-app-backend:${{ env.IMAGE_TAG }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push-backend
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up image tag from Git commit SHA
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/three-tier-app-web:${{ env.IMAGE_TAG }} .

      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/three-tier-app-web:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/three-tier-app-web:${{ env.IMAGE_TAG }}
